/* eslint-disable @typescript-eslint/no-explicit-any */

export function addSchemaDocumentation(schema: Record<string, any>) {
  return {
    $comment:
      "🧩 This file is auto-generated by env-checkup. You can edit or extend it manually to define validation rules.",
    $description:
      "Each key below represents an environment variable. You can add extra validation fields like `min`, `max`, `regex`, `enum`, `sensitive`, etc.",
    $typeDocs: {
      String: {
        description: "Plain string value (default type).",
        supports: ["minLength", "maxLength", "regex", "trim", "sensitive"],
        example: { type: "String", minLength: 3, maxLength: 255, trim: true },
      },
      Number: {
        description: "Numeric value (integer or float).",
        supports: ["min", "max"],
        example: { type: "Number", min: 0, max: 1000 },
      },
      Boolean: {
        description: "True/false value, supports common aliases like 'true', 'false', '1', '0'.",
        supports: ["default"],
        example: { type: "Boolean", default: false },
      },
      Url: {
        description: "HTTP/HTTPS URL value.",
        supports: ["regex", "sensitive"],
        example: {
          type: "Url",
          regex: "^https?:\\/\\/[^\\s/$.?#].[^\\s]*$",
          description: "Must start with http:// or https://",
        },
      },
      Email: {
        description: "Email address string (validated by regex).",
        supports: ["regex", "sensitive"],
        example: {
          type: "Email",
          regex: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
        },
      },
      Port: {
        description: "Port number between 0 and 65535.",
        supports: ["min", "max"],
        example: { type: "Port", min: 0, max: 65535 },
      },
      Enum: {
        description: "Restricted set of string or numeric values.",
        supports: ["enum", "default"],
        example: {
          type: "Enum",
          enum: ["development", "staging", "production"],
          default: "development",
        },
      },
      Json: {
        description: "JSON object value, validated for parsability.",
        supports: ["validate"],
        example: {
          type: "Json",
          description: "A JSON string that parses into an object.",
        },
      },
      Path: {
        description: "File or directory path string.",
        supports: ["regex", "trim"],
        example: { type: "Path", regex: "^[./a-zA-Z0-9_-]+$" },
      },
      Date: {
        description: "ISO date string or timestamp.",
        supports: ["min", "max"],
        example: {
          type: "Date",
          description: "Must be a valid ISO date string, e.g., 2025-11-05T10:00:00Z",
        },
      },
      Array: {
        description: "Comma-separated string converted into an array.",
        supports: ["minLength", "maxLength", "validate"],
        example: { type: "Array", minLength: 1, maxLength: 10 },
      },
      Custom: {
        description: "Custom user-defined validation rule.",
        supports: ["regex", "validate", "description"],
        example: {
          type: "Custom",
          regex: "^[A-Z]{3}-[0-9]{4}$",
          description: "Custom format, e.g., ABC-1234",
        },
      },
    },
    $examples: {
      Boolean: { type: "Boolean", default: false },
      String: { type: "String", minLength: 2, maxLength: 255 },
      Number: { type: "Number", min: 0, max: 9999 },
      Enum: { type: "Enum", enum: ["dev", "prod"] },
    },
    ...schema,
  };
}

export function inferEnvSchema(parsed: Record<string, string>) {
  const schema: Record<string, any> = {};

  for (const [key, value] of Object.entries(parsed)) {
    const field: Record<string, any> = {
      type: "String",
      required: true,
      description: `Environment variable: ${key}`,
    };

    if (isBoolean(value)) {
      field.type = "Boolean";
    } else if (isNumber(value)) {
      field.type = "Number";
      field.min = 0;
      field.max = 9999999;
    } else if (isPort(value)) {
      field.type = "Port";
      field.min = 0;
      field.max = 65535;
    } else if (isEmail(value)) {
      field.type = "Email";
      field.regex = "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$";
    } else if (isUrl(value)) {
      field.type = "Url";
      field.regex = "^https?:\\/\\/[^\\s/$.?#].[^\\s]*$";
    } else if (isJson(value)) {
      field.type = "Json";
    } else if (isUUID(value)) {
      field.type = "UUID";
      field.regex = "^[0-9a-f]{8}-[0-9a-f]{4}-[4][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$";
    } else if (isArray(value)) {
      field.type = "Array";
      field.minLength = 1;
    } else if (key.toUpperCase() === "NODE_ENV") {
      field.type = "Enum";
      field.enum = ["development", "staging", "production"];
    }

    schema[key] = field;
  }

  return schema;
}

export const isBoolean = (v: string) => ["true", "false"].includes(v.toLowerCase());
export const isNumber = (v: string) => !isNaN(Number(v)) && v.trim() !== "";
export const isPort = (v: string) => isNumber(v) && Number(v) >= 0 && Number(v) <= 65535;
export const isEmail = (v: string) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v);
export const isUrl = (v: string) => /^https?:\/\/[^\s/$.?#].[^\s]*$/.test(v);
export const isJson = (v: string) => {
  try {
    const obj = JSON.parse(v);
    return typeof obj === "object";
  } catch {
    return false;
  }
};
export const isUUID = (v: string) =>
  /^[0-9a-f]{8}-[0-9a-f]{4}-[4][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v);
export const isArray = (v: string) => v.includes(",") && !v.includes("=");
